server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: flexi-admin

# SpringDoc OpenAPI 配置（仅导出JSON，不启用UI）
springdoc:
  api-docs:
    enabled: true
  show-actuator: true

mybatis-plus:
  mapper-locations:
    - classpath*:**/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
  global-config:
    banner: true
